# Generated by Django 5.2.8 on 2025-11-06 04:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('PROMOCION', 'Promoción'), ('ESPECIAL', 'Especial')], default='GENERAL', max_length=50)),
                ('canal_venta', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista'), ('ECOMMERCE', 'E-commerce'), ('TODOS', 'Todos')], default='TODOS', max_length=50)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='empresas.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='empresas.sucursal')),
            ],
            options={
                'verbose_name': 'Lista de Precio',
                'verbose_name_plural': 'Listas de Precios',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CombinacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('articulos', models.ManyToManyField(blank=True, to='inventario.articulo')),
                ('grupos_articulo', models.ManyToManyField(blank=True, to='inventario.grupoarticulo')),
                ('lineas_articulo', models.ManyToManyField(blank=True, to='inventario.lineaarticulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='precios.listaprecio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrecioArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autorizado_bajo_costo', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_en_listas', to='inventario.articulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_articulos', to='precios.listaprecio')),
            ],
            options={
                'verbose_name': 'Precio de Artículo',
                'verbose_name_plural': 'Precios de Artículos',
                'unique_together': {('lista_precio', 'articulo')},
            },
        ),
        migrations.CreateModel(
            name='ReglaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_regla', models.CharField(choices=[('ESCALA_UNIDADES', 'Escala por Unidades'), ('MONTO_PEDIDO', 'Monto Total del Pedido'), ('COMBINACION', 'Combinación de Productos'), ('DESCUENTO_PROVEEDOR', 'Descuento Proveedor'), ('CANAL_VENTA', 'Canal de Venta Específico')], max_length=50)),
                ('prioridad', models.IntegerField(default=10)),
                ('cantidad_minima', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('cantidad_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('monto_minimo_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('canal_venta_especifico', models.CharField(blank=True, choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista'), ('ECOMMERCE', 'E-commerce'), ('TODOS', 'Todos')], max_length=50, null=True)),
                ('precio_fijo_resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Ej. 50.00 para 50%', max_digits=5, null=True)),
                ('aplica_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo')),
                ('aplica_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.grupoarticulo')),
                ('aplica_linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lineaarticulo')),
                ('combinacion_requerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.combinacionproducto')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='precios.listaprecio')),
            ],
            options={
                'verbose_name': 'Regla de Precio',
                'verbose_name_plural': 'Reglas de Precios',
                'ordering': ['lista_precio', 'prioridad'],
                'unique_together': {('lista_precio', 'prioridad')},
            },
        ),
    ]
