# Generated by Django 5.2.8 on 2025-11-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacionproducto',
            name='articulos',
            field=models.ManyToManyField(blank=True, related_name='combinaciones_articulo', to='inventario.articulo'),
        ),
        migrations.AlterField(
            model_name='combinacionproducto',
            name='grupos_articulo',
            field=models.ManyToManyField(blank=True, related_name='combinaciones_grupo', to='inventario.grupoarticulo'),
        ),
        migrations.AlterField(
            model_name='combinacionproducto',
            name='lineas_articulo',
            field=models.ManyToManyField(blank=True, related_name='combinaciones_linea', to='inventario.lineaarticulo'),
        ),
        migrations.AlterField(
            model_name='reglaprecio',
            name='aplica_articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_articulo', to='inventario.articulo'),
        ),
        migrations.AlterField(
            model_name='reglaprecio',
            name='aplica_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_grupo', to='inventario.grupoarticulo'),
        ),
        migrations.AlterField(
            model_name='reglaprecio',
            name='aplica_linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_linea', to='inventario.lineaarticulo'),
        ),
        migrations.AlterField(
            model_name='reglaprecio',
            name='combinacion_requerida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_combinacion', to='precios.combinacionproducto'),
        ),
        migrations.AlterField(
            model_name='reglaprecio',
            name='prioridad',
            field=models.IntegerField(default=10, help_text='Menor número = mayor prioridad'),
        ),
        migrations.CreateModel(
            name='DescuentoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base antes del descuento', max_digits=10)),
                ('precio_final', models.DecimalField(decimal_places=2, help_text='Precio final aplicado', max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento aplicado', max_digits=5)),
                ('costo_articulo', models.DecimalField(decimal_places=2, help_text='Costo del artículo al momento del descuento', max_digits=10)),
                ('canal_venta', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista'), ('ECOMMERCE', 'E-commerce'), ('TODOS', 'Todos')], max_length=50)),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad del artículo en el pedido')),
                ('monto_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('autorizado_por', models.CharField(blank=True, help_text='Usuario que autorizó el descuento', max_length=255)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el descuento')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_proveedor', to='inventario.articulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_proveedor', to='precios.listaprecio')),
            ],
            options={
                'verbose_name': 'Descuento de Proveedor',
                'verbose_name_plural': 'Descuentos de Proveedor',
                'ordering': ['-creado_en'],
            },
        ),
    ]
